### ISSUE TITLE
layuimini分支配置完，用管理员登录，没有管理员的权限

### ISSUE THREAD

**Issue by LoseRecall** [974988176/StudentCMS#1]
跟学生的权限一样

**Comment by 974988176** [comment]
@LoseRecall 可以截图看一下吗?目前来说,学生和管理员的区别是,管理员可以编辑,但学生会不显示所有元素的编辑功能

**Comment by 974988176** [comment]
@LoseRecall 如果有需要的话,你可以加我的qq:974988176

**Comment by 974988176** [comment]
已修复这人问题,问题原因是在db:seed时,未进行管理员角色的创建,现已修复
